### ISSUE TITLE
adding Hungarian

### ISSUE THREAD

**Issue by martino-vic** [dictionaria/dictionaria#103]
Hello everybody,

I'm working with Hungarian etymological data in my research, and came to realise that it would make sense to standardise them first. [I first went for a cldf-wordlist](https://github.com/martino-vic/gerstnerhungarian/issues/3), but as it turned out, a dictionary would be more fitting. So now I was wondering: Would there be interest in adding this data set to dictionaria?

**Comment by LinguList** [comment]
As the person who introduced you to dictionaria, I should maybe tell you that Dictionaria has some specific focus: they need glossed examples (IGT to illustrate how words are used for many of the entries), and they only publish original new dictionaries, not resources digitized by others.

**Comment by martino-vic** [comment]
Ah, I wasn't aware of that, sorry. I think I can close the issue then.
